import express from 'express';
import { upload, uploadResume, getResumes, getResume, analyzeATS, deleteResume } from '../controllers/resumeController.js';
import { authenticate } from '../middleware/auth.js';
const router = express.Router();
router.use(authenticate);
router.post('/upload', upload.single('resume'), uploadResume);
router.post('/ats', analyzeATS);
router.get('/', getResumes);
router.get('/:id', getResume);
router.delete('/:id', deleteResume);
export default router;
