import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';

const FEATURES = [
  { icon:'◈', title:'AI-Powered Questions', desc:'Domain-specific questions generated by Mistral AI, adapting to your experience level in real time.' },
  { icon:'◎', title:'ATS Resume Scoring', desc:'Upload your resume and get an instant ATS compatibility score with keyword gap analysis and suggestions.' },
  { icon:'◉', title:'Emotion Intelligence', desc:'Facial emotion detection tracks your confidence, nervousness, and engagement throughout the interview.' },
  { icon:'◧', title:'Speech Analytics', desc:'Filler word detection, pacing analysis, and communication scoring give you actionable voice feedback.' },
  { icon:'◷', title:'Video Interview Sim', desc:'WebRTC-powered camera feed for a realistic interview environment with live emotion overlay.' },
  { icon:'⬡', title:'Performance Reports', desc:'Detailed post-interview reports with AI recommendations, score breakdowns, and improvement roadmaps.' }
];

export default function Landing() {
  return (
    <div className="min-h-screen bg-void text-[#f1f5f9] overflow-hidden">
      <div className="fixed inset-0 grid-bg opacity-60 pointer-events-none" />
      <div className="fixed top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-[#6366f1]/8 rounded-full blur-3xl pointer-events-none" />
      <nav className="relative z-10 flex items-center justify-between px-8 py-5 border-b border-[#1e1e2e]/50 glass">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-[#6366f1] glow-accent flex items-center justify-center"><span className="text-white font-display font-bold text-sm">N</span></div>
          <span className="font-display font-bold text-xl">NexusAI</span>
        </div>
        <div className="flex items-center gap-4">
          <Link to="/login" className="btn-ghost text-sm py-2 px-4">Sign In</Link>
          <Link to="/register" className="btn-primary text-sm py-2 px-4">Get Started</Link>
        </div>
      </nav>
      <section className="relative z-10 pt-24 pb-20 px-8 text-center max-w-5xl mx-auto">
        <motion.div initial={{ opacity:0, y:30 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.7 }}>
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass border border-[#6366f1]/30 text-[#6366f1] text-xs font-display font-medium tracking-wider mb-8">
            <span className="w-1.5 h-1.5 rounded-full bg-[#6366f1] animate-pulse-slow" /> AI-POWERED INTERVIEW PLATFORM
          </div>
          <h1 className="font-display font-bold text-6xl md:text-7xl leading-tight mb-6">
            Ace Every Interview<br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#6366f1] via-[#818cf8] to-[#06b6d4]">With AI Precision</span>
          </h1>
          <p className="font-body text-[#94a3b8] text-xl max-w-2xl mx-auto mb-10 leading-relaxed">Practice with AI interviewers, analyze your resume with ATS scoring, detect emotions in real-time, and receive comprehensive feedback to land your dream job.</p>
          <div className="flex items-center justify-center gap-4 flex-wrap">
            <Link to="/register" className="btn-primary text-base py-4 px-8">Start Free Interview →</Link>
            <Link to="/login" className="btn-ghost text-base py-4 px-8">View Demo</Link>
          </div>
        </motion.div>
        <motion.div initial={{ opacity:0, y:40 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.8, delay:0.3 }} className="mt-16 grid grid-cols-2 md:grid-cols-4 gap-6">
          {[['94%','Interview Success Rate'],['10K+','Interviews Conducted'],['40+','Job Domains'],['4.9★','User Rating']].map(([v,l],i)=>(
            <div key={i} className="card text-center"><div className="font-display font-bold text-3xl text-[#6366f1] mb-1">{v}</div><div className="font-body text-[#94a3b8] text-sm">{l}</div></div>
          ))}
        </motion.div>
      </section>
      <section className="relative z-10 py-20 px-8 max-w-6xl mx-auto">
        <div className="text-center mb-14">
          <h2 className="font-display font-bold text-4xl mb-4">Everything You Need to Succeed</h2>
          <p className="text-[#94a3b8] font-body max-w-xl mx-auto">A complete interview preparation platform powered by cutting-edge AI.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {FEATURES.map((f,i)=>(
            <motion.div key={i} initial={{ opacity:0, y:20 }} whileInView={{ opacity:1, y:0 }} transition={{ delay:i*0.1 }} viewport={{ once:true }} className="card hover:border-[#6366f1]/30 transition-all duration-300">
              <div className="w-10 h-10 rounded-xl bg-[#6366f1]/10 border border-[#6366f1]/20 flex items-center justify-center mb-4 text-[#6366f1] text-xl">{f.icon}</div>
              <h3 className="font-display font-semibold text-lg mb-2">{f.title}</h3>
              <p className="font-body text-[#94a3b8] text-sm leading-relaxed">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>
      <section className="relative z-10 py-20 px-8 text-center">
        <div className="max-w-2xl mx-auto card-glow">
          <h2 className="font-display font-bold text-4xl mb-4">Ready to Get Hired?</h2>
          <p className="font-body text-[#94a3b8] mb-8">Join thousands of candidates who upgraded their skills with NexusAI.</p>
          <Link to="/register" className="btn-primary text-lg py-4 px-10 inline-block">Create Free Account</Link>
        </div>
      </section>
      <footer className="relative z-10 border-t border-[#1e1e2e] px-8 py-6 text-center text-[#475569] text-sm font-body">© 2025 NexusAI — Powered by Mistral AI + WebRTC</footer>
    </div>
  );
}
