export const formatTime = (s) => { if (!s && s !== 0) return '00:00'; const m = Math.floor(s/60); return `${String(m).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`; };
export const formatDuration = (s) => { if (!s) return 'N/A'; if (s < 60) return `${s}s`; return `${Math.floor(s/60)}m ${s%60}s`; };
export const formatDate = (date, opts={}) => { if (!date) return ''; return new Date(date).toLocaleDateString('en-US', { month:'short', day:'numeric', year:'numeric', ...opts }); };
export const scoreColor = (score) => score >= 80 ? '#10b981' : score >= 60 ? '#f59e0b' : '#f43f5e';
export const scoreLabel = (score) => score >= 85 ? 'Excellent' : score >= 70 ? 'Good' : score >= 55 ? 'Average' : score >= 40 ? 'Below Average' : 'Needs Improvement';
export const capitalize = (str) => !str ? '' : str.charAt(0).toUpperCase() + str.slice(1);
export const truncate = (str, max=80) => !str ? '' : (str.length > max ? str.slice(0,max) + '…' : str);
export const getInitials = (name) => !name ? '?' : name.split(' ').map(n=>n[0]).slice(0,2).join('').toUpperCase();
export const sleep = (ms) => new Promise(r => setTimeout(r, ms));
export const debounce = (fn, delay) => { let timer; return (...args) => { clearTimeout(timer); timer = setTimeout(()=>fn(...args), delay); }; };
